### ISSUE TITLE
DotNetCoreMSBuildSettings UseToolVersion(...) not working

### ISSUE THREAD

**Issue by maldworth** [cake-build/cake#2549]
### What You Are Seeing?
Been successfully using `DotNetCoreBuild(..., settings)` for a while, and after installing VS2019 started getting build errors because it installed MSBuild16. Before that, only had VS2017 installed, and MSBuild 15.9.X.

When I look in:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin`
v 15.9.X is still there

and in
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin` the new 16.X is present.

so I tried to use the settings flag to specify I want the older MSBuild

`settings.MSBuildSettings = new DotNetCoreMSBuildSettings().UseToolVersion(MSBuildVersion.MSBuild15)`

I get this error:

```
Microsoft (R) Build Engine version 16.0.450+ga8dc7f1d34 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1040: ToolsVersion is not valid. The tools version "15.0" is unrecognized. Available tools versions are "Current".
Switch: 15.0
```
### What is Expected?
The UseToolVersion to override the default MSBuild 16 to use version 15 instead

### What version of Cake are you using?
0.32.1

### Are you running on a 32 or 64 bit system?
yes 64-bit

### What environment are you running on?  Windows? Linux? Mac?
Windows 10

### Are you running on a CI Server?  If so, which one?
It also happens on Appveyor VS2017 image

**Comment by devlead** [comment]
This should be fixed in the latest version of Cake.

**Comment by HyderNBK117** [comment]
Hello, this issue is still happening? tried in Cake verduins 0.30.0, 0.33.0 and 0.35.0
